"""
SatQuery AI — ChangeFormer Hugging Face Space Endpoint
Space ID: Sanika2006/satquery-changeformer

Official Architecture: wgcban/ChangeFormer (ChangeFormerV6)
Pretrained Checkpoint: LEVIR-CD (checkpoints/ChangeFormer_LEVIR/best_ckpt.pt)

Bi-temporal Change Detection model microservice for satellite imagery.
Accepts two base64-encoded PNG images (Image 1 pre-change, Image 2 post-change)
and returns a base64-encoded PNG change heatmap generated by genuine ChangeFormerV6.
"""
import io
import os
import sys
import base64
import numpy as np
from PIL import Image
import gradio as gr

# Ensure local models directory is in python path
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
if BASE_DIR not in sys.path:
    sys.path.insert(0, BASE_DIR)

import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.transforms as transforms

try:
    import cv2
    CV2_AVAILABLE = True
except ImportError:
    CV2_AVAILABLE = False

from models.ChangeFormer import ChangeFormerV6


# ── Model & Checkpoint Paths ──────────────────────────────────────────────────
MODEL_NAME = "ChangeFormerV6 (LEVIR-CD)"
CHECKPOINT_DIR = os.path.join(BASE_DIR, "checkpoints", "ChangeFormer_LEVIR")
CHECKPOINT_PATH = os.path.join(CHECKPOINT_DIR, "best_ckpt.pt")

_model = None
_model_load_error = None


def decode_base64_image(b64_str: str) -> Image.Image:
    """Decode a base64 string (with or without data URI header) into a PIL Image."""
    if not b64_str or not isinstance(b64_str, str):
        raise ValueError("Invalid base64 image string.")

    if "," in b64_str:
        b64_str = b64_str.split(",", 1)[1]

    img_bytes = base64.b64decode(b64_str)
    img = Image.open(io.BytesIO(img_bytes)).convert("RGB")
    return img


def encode_image_base64(img: Image.Image) -> str:
    """Encode a PIL Image into a base64 PNG string."""
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return base64.b64encode(buf.getvalue()).decode("utf-8")


def load_changeformer_model() -> ChangeFormerV6:
    """
    Load the genuine ChangeFormerV6 model with official LEVIR-CD pretrained state_dict.
    Fails explicitly if the checkpoint is missing or incompatible.
    """
    global _model, _model_load_error

    if _model is not None:
        return _model

    if not os.path.exists(CHECKPOINT_PATH):
        _model_load_error = (
            f"Pretrained ChangeFormer checkpoint missing at: '{CHECKPOINT_PATH}'. "
            f"Please ensure 'best_ckpt.pt' is present in '{CHECKPOINT_DIR}'."
        )
        raise RuntimeError(_model_load_error)

    try:
        # Load weights checkpoint using PyTorch
        ckpt = torch.load(CHECKPOINT_PATH, map_location="cpu", weights_only=False)
        state_dict = ckpt["model_G_state_dict"] if isinstance(ckpt, dict) and "model_G_state_dict" in ckpt else ckpt

        # Instantiate ChangeFormerV6 (embed_dim=256, output_nc=2 for LEVIR-CD)
        model = ChangeFormerV6(embed_dim=256, output_nc=2)
        model.load_state_dict(state_dict, strict=True)
        model.eval()

        _model = model
        return _model
    except Exception as exc:
        _model_load_error = f"Failed to load genuine ChangeFormerV6 checkpoint: {str(exc)}"
        raise RuntimeError(_model_load_error)


def run_changeformer_inference(img1: Image.Image, img2: Image.Image) -> Image.Image:
    """
    Preprocess bi-temporal images, run genuine ChangeFormerV6 forward pass,
    and convert output prediction mask to a visual PNG change map.
    """
    model = load_changeformer_model()

    # Preprocessing for 256x256 image pairs
    target_size = (256, 256)
    img1_resized = img1.resize(target_size, Image.Resampling.BILINEAR)
    img2_resized = img2.resize(target_size, Image.Resampling.BILINEAR)

    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5]),
    ])

    t1 = transform(img1_resized).unsqueeze(0)  # Shape: [1, 3, 256, 256]
    t2 = transform(img2_resized).unsqueeze(0)  # Shape: [1, 3, 256, 256]

    with torch.no_grad():
        output = model(t1, t2)
        if isinstance(output, (tuple, list)):
            output = output[0]

        # Bilinear interpolation back to full resolution (256, 256)
        output_256 = F.interpolate(output, size=target_size, mode="bilinear", align_corners=True)

        # Argmax binary change mask prediction (0 = Unchanged, 1 = Changed)
        preds = torch.argmax(output_256, dim=1).squeeze(0).cpu().numpy()

    # Convert binary change mask [0, 1] to uint8 heatmap [0, 255]
    mask = (preds * 255).astype(np.uint8)

    if CV2_AVAILABLE:
        # Apply JET colormap (Blue = Unchanged, Red = High Change Intensity)
        colored_mask = cv2.applyColorMap(mask, cv2.COLORMAP_JET)
        rgb_mask = cv2.cvtColor(colored_mask, cv2.COLOR_BGR2RGB)
        return Image.fromarray(rgb_mask)
    else:
        return Image.fromarray(mask, mode="L").convert("RGB")


def predict(image1_b64: str, image2_b64: str) -> str:
    """
    Gradio predict endpoint.
    API Contract:
        Inputs: {"data": [image1_b64, image2_b64]}
        Outputs: {"data": [change_map_b64]}
    """
    # 1. Validate exactly two image inputs
    if not image1_b64 or not image2_b64:
        raise gr.Error("ChangeFormer requires exactly two base64-encoded image inputs (Image 1 and Image 2).")

    # 2. Decode inputs
    try:
        img1 = decode_base64_image(image1_b64)
        img2 = decode_base64_image(image2_b64)
    except Exception as exc:
        raise gr.Error(f"Failed to decode base64 input images: {str(exc)}")

    # 3. Execute genuine ChangeFormer inference
    try:
        change_map_img = run_changeformer_inference(img1, img2)
        return encode_image_base64(change_map_img)
    except RuntimeError as rerr:
        raise gr.Error(f"ChangeFormer Model Error: {str(rerr)}")
    except Exception as exc:
        raise gr.Error(f"ChangeFormer Inference Failed: {str(exc)}")


# Gradio interface (API endpoint /run/predict)
demo = gr.Interface(
    fn=predict,
    inputs=[
        gr.Textbox(label="Image 1 (Base64 PNG)", lines=2),
        gr.Textbox(label="Image 2 (Base64 PNG)", lines=2),
    ],
    outputs=[
        gr.Textbox(label="Change Map (Base64 PNG)", lines=2),
    ],
    title="SatQuery AI — Official ChangeFormer V6 Endpoint",
    description="Bi-temporal satellite change detection microservice using ChangeFormerV6 (LEVIR-CD).",
    api_name="predict",
)

if __name__ == "__main__":
    demo.launch(server_name="0.0.0.0", server_port=7860)
